### ISSUE TITLE
What license is this code released under?

### ISSUE THREAD

**Issue by dflock** [henriquesakata/vuejs-keycloak#1]
Things that you create and don't specify a license for a copyrighted to you, and not usable by others without explicit permission.

As far as I can see, there's no license specified for this, so anyone who wants to use it would need to get permission directly from you for each use.

Is this intentional? If not, you should specify the license, so others can use it.

**Comment by henriquesakata** [comment]
I'm sorry, it wasn't intentional.

Updated now.
